### ISSUE TITLE
The Machines

### ISSUE THREAD

**Issue by Fortist** [T145/ThermalSmeltery-Redux#1]
Those are gone, and also the Potato stuff is gone.
The Voiding shard is also gone, but I assume the latter two were removed purposefully, the machines worked, at least the casting one.

**Comment by T145** [comment]
Yes,  everything was removed intentionally. The machines because while they may have worked were still very incomplete (untested, had no recipes, had no basic-resonant variants, etc.). Everything else was removed because those features are all provided by other mods. Now if everything was complete, I would've ported them, but since there seems to be a lot of a public upset around those unusable features, it just seems logical to give people what they're told they are getting; including no more and no less.

**Comment by Fortist** [comment]
Untested, probably.
The Ingot and block casting machine worked, it had recipes for basic to resonant, if thats what you mean by recipes. I straight up never used the Part caster, so I wont really comment on it.
At least look into the former machine,
